### PR TITLE
Updated node-forge.

### PR DESCRIPTION
**Pull request by Jokerwolf**
Trying to resolve this issue https://github.com/webpack/webpack-dev-server/issues/1702

I'm not an expert sorry. 
Ran the tests, updated, ran the tests. All green.

### CODE REVIEW

**Comment by yingliang33h** [comment]
@Jokerwolf  this is what we got when run the content detection:

Description
This component was not approved for the following reasons:
====================================
TLS 1.2 not implemented yet, maybe in 0.8 per roadmap, but that release may only be prep-work for future implementation:
https://github.com/digitalbazaar/forge/issues/203

TLS does not check for acceptable cipher suite configurations. From "tls.js":
// FIXME: should be checking configured acceptable cipher suites

TLS client connections may only support TLS_RSA_WITH_AES_128_CBC_SHA & TLS_RSA_WITH_AES_256_CBC_SHA
https://github.com/digitalbazaar/forge/issues/600

Does not check for revoked certificates; From "x509.js":
===================================

**Comment by yingliang33h** [comment]
@Jokerwolf  evilebottnawi's  fix would solve the problem, could you please merger his PR?

**Comment by Jokerwolf** [comment]
@yingliang33h sorry, seems like i don't have write access to merge this PR. (

**Comment by evilebottnawi** [comment]
I can't have merge access

**Comment by jfromaniello** [comment]
thank you and sorry for the delay.. I've released this as `v1.10.5`

**Comment by yingliang33h** [comment]
@jfromaniello Thanks a lot!
@evilebottnawi could we kick off a new release of webpack-dev-server with the release above? 

Thanks so much guys!

**Comment by calebhskim** [comment]
@jfromaniello is there any update as to when the new version will be published? I might be missing something but checking https://www.npmjs.com/package/selfsigned the latest version is still v1.10.4? I am currently forcing `selfsigned` to take a dependency on node-forge@0.8.5 Thanks!

**Pull request merged**
