### PR TITLE
Default keySize to 2048 and respect in all keys (fixes #33)

### LINKED ISSUE #33: SSL routines:SSL_CTX_use_certificate:ee key too small
https://github.com/jfromaniello/selfsigned/blob/7bd58764439eee6198895338fd2f6e388f5833d0/index.js#L113

```javascript
    var opts = {
        keySize: 2048,
        algorithm: 'sha256',
        days: 365 * 10,
        clientCertificate: true,
        clientCertificateCN: 'client_name'
      }
```
var pems = await selfsigned.generate(attrs, opts)

Trying use the client certificate to connect to the server. In this case MQTT.JS connecting to AEDES.

On debian I receive the error message

`Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small`

OpenSSL 1.1.1d  10 Sep 2019

Only way around it is to modify:  /etc/ssl/openssl.cnf and change:

CipherString = DEFAULT@SECLEVEL=2
to
CipherString = DEFAULT@SECLEVEL=1

I believe the issue is the referenced issue above and generating the client certificates as 1024 bit. SECLEVEL=2 requires minimum of 2048 bit.

Expose a option for clientCertificateKeySize just like you use keySize for the server side and that should satisfy the requirements.  That or just use keySize for both would be fine as well.

### PR DESCRIPTION
**Pull request by blahah**

### CODE REVIEW

**Comment by julien-f** [comment]
@jfromaniello Any chance of seeing this merged?

**Comment by blahah** [comment]
Not sure why it is failing but if it would help I can look into it this weekend

**Comment by dxdc** [comment]
@blahah I think the problem is most likely the amount of time allocated for testing. I modified the testing time (see: https://github.com/jfromaniello/selfsigned/pull/36) and included your commit but I guess travis testing doesn't run automatically?

**Comment by jfromaniello** [comment]
Sorry for the long delay, both key size can be changed with an option now.
There is a keySize and clientCertificateKeySize.

The default is still 1024. I will consider changing the default value in a major release.

**Pull request closed without merging**
