### PR TITLE
feat: add typescript support

### LINKED ISSUE #19: Typescript support
I couldn't find the typescript definitions for this package, and I know there's not too much properties but it would be nice to have this support in case you're not working on it.

### PR DESCRIPTION
**Pull request by danielroe**
resolves #19

### CODE REVIEW

**Comment by prescience-data** [comment]
👀 This would be awesome

**Comment by mutantcornholio** [comment]
@jfromaniello any chance on merging this?

**Comment by jfromaniello** [comment]
Thank you! published as v2.1.0

**Comment by mutantcornholio** [comment]
@jfromaniello doesn't seem to be published in npm though: https://www.npmjs.com/package/selfsigned

**Comment by mutantcornholio** [comment]
Thanks!

**Pull request merged**
